### ISSUE TITLE
PHP language level

### ISSUE THREAD

**Issue by mikevandiepen** [JKetelaar/PHP-Kiyoh-API#12]
Hi,

I have noticed that you make use of a lot of strictly typed practices like typehinting and using return types, yet in your composer.json file you have the basic PHP language level of ^5.5 || ^7.0.

Since TypeHinting for variables and return types has been introduced since 7.1 is this not that smart. Either update your PHP version in composer.json or add backwards compatibility for older PHP versions.

Also nullable return types are not valid below 7.1.

**Comment by JKetelaar** [comment]
Hi, I totally forgot to change the PHP level to ~7.1 after the revision of recently. I will include this in the upcoming cleanup.

**Comment by JKetelaar** [comment]
Fixed in commit 6682bf4
