### ISSUE TITLE
URL for all reviews ?

### ISSUE THREAD

**Issue by f3bruary** [JKetelaar/PHP-Kiyoh-API#3]
Is there also a URL available for all reviews, instead of just the recent ones ?

**Comment by JKetelaar** [comment]
The API doesn’t provide that functionality unfortunately. Would you could do, is loop through all the recent reviews with pagination.

**Comment by f3bruary** [comment]
Which URL parameter does this? Do you have an example perhaps? 

EDIT: I must have misunderstood. You probably mean to loop through the same output from recent_company_reviews.xml

**Comment by JKetelaar** [comment]
Update: This now works in the latest version
