### ISSUE TITLE
PHP8 support

### ISSUE THREAD

**Issue by fruitl00p** [JKetelaar/PHP-Kiyoh-API#37]
I've gone ahead and created several merge requests to bring the project up to par (or atleast support PHP8)

I've created them in succesion which shoul alleviate the review burden. 

The project should support PHP8 out of the box (mostly) but the first MR 'codifies' this. ( #34 )
Next i've gone ahead and updated various files and dependencies to utilize the PHP of today ( #35 )
This would be the last 'status' that would support PHP7.
Finally the last MR should drop PHP7 support and utilize the modern tricks one can now do with PHP. ( #36 )

Hope you can merge these as we'd like to keep using this library with PHP8

**Comment by JKetelaar** [comment]
Hi @fruitl00p - thanks for the awesome work, this is highly appreciated!

How do you feel about releasing v3.0 with the changes for PHP 8+ support? Instead of doing this within v2.x.

**Comment by fruitl00p** [comment]
That's up to you primarily and would follow several nicely. It also leaves the ability for older clients to keep churning on older PHP

**Comment by JKetelaar** [comment]
PHP 8 is now available with version 2.1.0
