### ISSUE TITLE
Amount of total reviews returned by Kiyoh endpoint is not correct

### ISSUE THREAD

**Issue by menno-ll** [JKetelaar/PHP-Kiyoh-API#6]
Hi @JKetelaar,

I've discovered that the total amount of reviews `default->company->total_reviews` returned by the `https://www.kiyoh.nl/xml/recent_company_reviews.xml` endpoint is not updating anymore.

Therefore I think that maybe Kiyoh has discontinued that feed endpoint.

However, it looks like they have a new one available.
That one is returning the correct amount of total reviews.
You can find it via your Kiyoh account, under `Publish->Extra options->XML-feed`.
The feed url looks like this: `https://www.kiyoh.com/v1/review/feed.xml?hash=HASH_HERE`
Maybe we should use that one instead?

**Comment by JKetelaar** [comment]
Ah good catch, I will look into it later today.
Seems like they updated their feed without notice to any customer, but oh well...

**Comment by menno-ll** [comment]
Oh wow today already, that's quick! Thanks in advance for looking into it :).
It's indeed not very nice that they didn't inform their customers.
But it may be a bug on their side that the old feed isn't updating, i don't know :S.
If there's something I can help you with or other info you need, feel free to ask!

**Comment by JKetelaar** [comment]
I have contacted Kiyoh to see what their status is on the feed and see if this is done on purpose or if we should move to a new endpoint. To be honest, I'm not expecting a response, but it's worth looking into their opinion before we move to another endpoint.

If I have no response before the end of the weekend, I will move the module as soon as possible to the new endpoint.

**Comment by menno-ll** [comment]
In the meantime our customer has also received a notification from Kiyoh.
I've translated it to English for you, and included the original (Dutch) message below the English one. This is about the invite API, but it may be useful for the Rating feed here as well.

In English:

> Shortly the review systems Kiyoh and Klantenvertellen (systems for star ratings withing Googe) will migrate to a new system. Therefore they also changed the integration between your website and their backend. When you still use the old system in October, new reviews will not be added to the star rating.
> 
> To maintain the correct clicktrough rating from Google, it's important that we make sure the new connection is set up. De developer of the website will need the data below to make the new conneciton work:
> 1. API Token
> 2. Location ID.
> 
> The information above can be found in your Kiyoh account. You need to perform the steps below:
> 1. Go to 'Invite' in the main menu
> 2. Click on 'Extra options'
> 3. Within the invite link there is a sequence of numbers. This is the Locaiton ID.
> 4. Below Invite Api there is a long line containing numbers, characters and dashes. That is the API token.
> 
> Can you make sure the web developer receives this information?

In Dutch:

> Binnenkort gaan reviewsystemen KiyOh en Klantenvertellen (systemen voor de sterrenrating binnen Google) over op een nieuw systeem. Hierbij hebben zij ook de koppeling tussen jouw website en hun backend aangepast. Wanneer in oktober nog gebruik gemaakt wordt van het oude systeem, dan worden de nieuwe beoordelingen niet meer opgenomen binnen de sterrenrating.
> 
> Om een goede doorklikratio van Google te behouden is het belangrijk dat we ervoor zorgen dat de nieuwe koppeling tot stand gebracht is. De onderstaande gegevens heeft de webbouwer nodig om de nieuwe koppeling werkend te maken: 
> 1. API Token
> 2. Locatie ID
> 
> De bovenstaande informatie kun je vinden binnen jouw Kiyoh account. Hiervoor moet je de volgende stappen gebruiken: 
> 1. Ga naar ‘Uitnodigen’ in het hoofdmenu
> 2. Klik op ‘Extra opties’
> 3. Binnen de Invite link staat een getallenreeks, dit is de Locatie ID
> 4. Onder Invite Api staat een lange regel van cijfers, letters en daar tussenin streepjes. Dit is de API token. 
> 
> Wil je ervoor zorgen dat de webbouwer deze gegevens krijgt?

**Comment by JKetelaar** [comment]
Thanks a lot, I will dive into it right now!

**Comment by menno-ll** [comment]
Hi @JKetelaar, 
Thanks for wanting to look into it, how is everything going so far?
If there is anything I can assist you with, feel free to ask!

**Comment by JKetelaar** [comment]
Hi there!

Sorry for the late reply, I have been very busy over the last week.
I have rewritten the API, just some final tests I have to do before I can push it.

Unfortunately, their entire backbone has changed, which means I also needed to make some breaking changes. Therefore this version update will be a major update.

**Comment by menno-ll** [comment]
Hey, no worries, i understand :).

I also saw the structure changed a lot, and understand it will therefore be a major update.
Amazing to hear you were able to still do it so quickly.

I will be waiting for the release 👍  :D

**Comment by JKetelaar** [comment]
Thanks for the wait!

Created a pull request (#7 ) - Feel free to check it out

**Comment by menno-ll** [comment]
Not a problem at all, looking at the amount of changes... Wow... 

At first look, it looks like extremely clear code! It doesn't happen that often that you see such nice code.
I'm not able to look closely and test it yet, but I will try to see if I can test it inside a project next week. :)

**Comment by JKetelaar** [comment]
Thanks for the kind words. I am currently implementing this version with a few of my clients, which seems to be working fine. Once validated by the clients, I will merge this and push it to Packagist.

Keep me updated on your progress.

**Comment by menno-ll** [comment]
I'm testing currently and only found one issue so far. 
The `ReviewContent` Model class, `getRating` / `setRating` function.
A ReviewContent rating can be of different types, not always a float.
For example, our client has some values there which are strings.
I will copy an example of a ReviewContent XML object below. Please see the `questionType` property. 
Maybe we should consider removing the casting or cast it based on the `questionType` property.

```xml
<reviewContent>
<reviewContent>
<questionGroup>DEFAULT_OVERALL</questionGroup>
<questionType>INT</questionType>
<rating>8</rating>
<order>0</order>
<questionTranslation>Totaal score</questionTranslation>
</reviewContent>
<reviewContent>
<questionGroup>DEFAULT_ONELINER</questionGroup>
<questionType>TEXT</questionType>
<rating>Zeer leerzaam, toepasbaar en leuk</rating>
<order>0</order>
<questionTranslation>Beschrijf uw ervaring in een regel</questionTranslation>
</reviewContent>
<reviewContent>
<questionGroup>DEFAULT_OPINION</questionGroup>
<questionType>TEXT</questionType>
<rating>
Erg leerzame cursus, die goed toepasbaar zijn in het dagelijks leven en op kantoor. Het werd door beide personen goed en duidelijk gebracht, op een leuke manier, waardoor het goed te volgen was en je gemakkelijk je aandacht er bij kon houden.
</rating>
<order>0</order>
<questionTranslation>Beschrijf uw ervaring</questionTranslation>
</reviewContent>
<reviewContent>
<questionGroup>DEFAULT_RECOMMEND</questionGroup>
<questionType>BOOLEAN</questionType>
<rating>true</rating>
<order>0</order>
<questionTranslation>Aanbevelen?</questionTranslation>
</reviewContent>
</reviewContent>
```

**Comment by menno-ll** [comment]
I've contacted Kiyoh to hopefully retreive documentation for the endpoint, to see which `questionType` values are possible.

**Comment by JKetelaar** [comment]
Thanks for the review @menno-ll, this is highly appreciated!

Regarding to the rating text, this is quite bad practice (from KiyOh)...
I might create an array of reviews with a filterable on text-reviews and number-reviews. I'll think about it.

Thanks again!

**Comment by JKetelaar** [comment]
Moved to issue #9
