### ISSUE TITLE
Uncertain endpoint results

### ISSUE THREAD

**Issue by JKetelaar** [JKetelaar/PHP-Kiyoh-API#9]
Apparently `rating` within a review can be both a number and a string.

@menno-ll has contacted KiyOh to get documentation regarding their endpoints and see what they describe as results.

_Comes from issue #6_

**Comment by menno-ll** [comment]
For now I received the response from Kiyoh that they don't have feed implementation documentation, but only API implementation. So I think they didn't understand what I wanted. 
So I asked if they can send me the API documentation, still waiting for a response for that request.

**Comment by menno-ll** [comment]
I've got the documentation which contains exactly what we need 😃 . I've created a temp url, which should expire in 2 weeks (because I don't think they want me to forever publicly share the documentation here...).

https://file.io/eKuhNA

**Comment by JKetelaar** [comment]
It says 404 Page not found 😢

**Comment by menno-ll** [comment]
~😲 ok, well here you go then :) (will delete the comment after you've downloaded it)~

**Comment by JKetelaar** [comment]
Got it, thank you!
